// File generated by flutterfire_cli.
// DO NOT EDIT. This file is used to store Firebase options and should be committed to version control.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWGOVyzDjrpfsV2Awe4-X6bpyiUwkt_CI',
    appId: '1:869641026445:web:59a1ace7bf8cbc804edbc4',
    messagingSenderId: '869641026445',
    projectId: 'study-companion-5f354',
    authDomain: 'study-companion-5f354.firebaseapp.com',
    storageBucket: 'study-companion-5f354.firebasestorage.app',
    measurementId: 'G-B5F47847VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoUy205HARXHACb9Tp3k02QSrKqFNC6M',
    appId: '1:869641026445:android:3b82772f726ca9914edbc4',
    messagingSenderId: '869641026445',
    projectId: 'study-companion-5f354',
    storageBucket: 'study-companion-5f354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA67V2zg_DJTF64AjaxmmG-8U7KTglya9Y',
    appId: '1:869641026445:ios:9fc2b143689066844edbc4',
    messagingSenderId: '869641026445',
    projectId: 'study-companion-5f354',
    storageBucket: 'study-companion-5f354.firebasestorage.app',
    iosBundleId: 'com.example.studycompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA67V2zg_DJTF64AjaxmmG-8U7KTglya9Y',
    appId: '1:869641026445:ios:9fc2b143689066844edbc4',
    messagingSenderId: '869641026445',
    projectId: 'study-companion-5f354',
    storageBucket: 'study-companion-5f354.firebasestorage.app',
    iosBundleId: 'com.example.studycompanionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWGOVyzDjrpfsV2Awe4-X6bpyiUwkt_CI',
    appId: '1:869641026445:web:0c655179b892d32f4edbc4',
    messagingSenderId: '869641026445',
    projectId: 'study-companion-5f354',
    authDomain: 'study-companion-5f354.firebaseapp.com',
    storageBucket: 'study-companion-5f354.firebasestorage.app',
    measurementId: 'G-TGVMH1SFDJ',
  );

}